### ISSUE TITLE
🧩 [1pt] Set Up Redux and Routing (Group Task) - [4H]

### ISSUE THREAD

**Issue by shogof** [shogof/space-travelers-hub#3]
**Description:**  
Set up the Redux store, actions, and reducer, and configure routing for the application.

**Assigned to:**

- **Roya:**  
  - Establish the Redux store in the `store.js` file and link it to the React app.

- **Marwa:**  
  - Create action types and action creators in the `actions.js` file to manage tasks.

- **Shogofa:**  
  - Develop the reducer logic in the `reducers.js` file to handle adding and toggling tasks.  
  - Implement routing with React Router to facilitate navigation among key components (e.g., Rockets, Missions, My Profile).

**Comment by Marwa-Sadat** [comment]
Thank you for assigning this to me
I will review it and provide feedback by

**Comment by ahzamir** [comment]
@shogof 

- Well done team, your kanban board contains all the necessary tasks needed for this amazing project now it's time to start working on them APPROVED Good luck ✅

**Comment by ahzamir** [comment]
@Marwa-Sadat 

This is not a code review task that you should provide feedback this is your project's tasks which is divided to individual and group tasks that you all need to finish and submit your project according to these tasks and plan.

**Comment by shogof** [comment]
@ahzamir 
Thank you! 🎉 We’re excited to get started on the tasks and make great progress on the project. We’ll keep the Kanban board updated and ensure everything is on track. Appreciate the approval and good luck to us all! ✅🚀
