### ISSUE TITLE
🧩[1pt] Set Up Navigation (Group Task) - [5H]

### ISSUE THREAD

**Issue by shogof** [shogof/space-travelers-hub#4]
**Description:**  
Create the navigation structure and set up routing for the application.

**Assigned to:**

- **Roya:**  
  - Create an empty navigation component (this will be filled in with separate tasks).
  - Download the free image for the app logo from [this link](https://www.flaticon.com/free-icon/planet_3212567?term=space&page=1&position=19&page=1&position=19&related_id=3212567&origin=style).

- **Shogofa:**  
  - Use `<NavLink />` for navigation links and style the active class to indicate which section/page the user is currently on (underline the active navigation link).  
  - Ensure the view component is initially empty; content will be added in future tasks.

**Comment by Marwa-Sadat** [comment]
Thank you for assigning this to me. I will review it and provide feedback
by
